### ISSUE TITLE
Docs for Stan 2.26 release - issue to track progress

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#298]
We are ~6 weeks away from the next release so I am creating an issue to track and highlight some of the older issues that are not huge projects and we can maybe get some help before the release.

New functions/signatures:
- [x] add docs for new overloads of size() https://github.com/stan-dev/docs/issues/120
- [ ] add docs for new overloads of log_mix() https://github.com/stan-dev/docs/issues/134
- [x] add documentation for new functions lambert_w0 and lambert_w1: https://github.com/stan-dev/docs/issues/200
- [x] expand docs on elementwise operations https://github.com/stan-dev/docs/issues/149
- [x] add docs for container construction utilities https://github.com/stan-dev/docs/issues/206
- [ ] document the new array syntax https://github.com/stan-dev/docs/issues/296

Miscelaneous (typos, inconsistencies, ...):
- [x] fix capitalization in titles https://github.com/stan-dev/docs/issues/154
- [x] explain the use of transpose operator in a example model: https://github.com/stan-dev/docs/issues/167
- [x] fix a typo in the dirichlet distribution: https://github.com/stan-dev/docs/issues/184
- [x] fix some between sections inconsistency https://github.com/stan-dev/docs/issues/196
- [x] fix typos in the MRP chapter https://github.com/stan-dev/docs/issues/249
- [ ] improve ODE docs https://github.com/stan-dev/docs/issues/282 https://github.com/stan-dev/docs/issues/283
- [x] typos in squared_distance https://github.com/stan-dev/docs/issues/291

#### Current Version:
v2.25.0

**Comment by jgabry** [comment]
I just checked off "fix capitalization in titles" because it looks like @Alanocallaghan just did that in https://github.com/stan-dev/docs/pull/299

**Comment by Alanocallaghan** [comment]
Also added #299 and #184 to that PR as they're minor, but I can revert and make separate PRs if you prefer

**Comment by jgabry** [comment]
Thanks! I think it's fine to add those minor things to the same PR instead of making separate ones just for those typos.

**Comment by Alanocallaghan** [comment]
I think #283 is the ODE issue not #286

**Comment by rok-cesnovar** [comment]
Thanks, I made a wrong edit, wanted to add 283 and 282.

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar and @jgabry , I think the [Poisson-binomial](https://github.com/stan-dev/math/blob/develop/stan/math/prim/prob/poisson_binomial_lcdf.hpp) distribution isn't documented yet, either. I can add it to the docu later that week, if that's fine with you.

**Comment by rok-cesnovar** [comment]
Hey Simon, that would be fantastic. You are correct poisson_binomial was not documented. Once you have the docs PR open, I will make sure to add it to stanc3 list of supported signatures (https://github.com/stan-dev/stanc3/issues/618).

**Comment by rok-cesnovar** [comment]
Two new docs issues that should be simple to tackle have been opened recently:

https://github.com/stan-dev/docs/issues/310 and https://github.com/stan-dev/docs/issues/308

**Comment by rok-cesnovar** [comment]
The 2.26 release is out, we squashed most of the issues. Thanks to all that contributed! 

Will close this issue, the open issues will still be available in the issue tracker.
